export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_SHARE_TO_MODAL = 'OPEN_SHARE_TO_MODAL';
export const CLOSE_SHARE_TO_MODAL = 'CLOSE_SHARE_TO_MODAL';
export const OPEN_SUCCESS_MODAL = 'OPEN_SUCCESS_MODAL';
export const CLOSE_SUCCESS_MODAL = 'CLOSE_SUCCESS_MODAL';
export const OPEN_NOTIFICATION_PANEL = 'OPEN_NOTIFICATION_PANEL';
export const CLOSE_NOTIFICATION_PANEL = 'CLOSE_NOTIFICATION_PANEL';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const ERASE_USER_DETAILS = 'ERASE_USER_DETAILS';
export const LOADING = 'LOADING';
export const GET_ALL_ASSET = 'GET_ALL_ASSET';
export const OPEN_DOCUMENT = 'OPEN_DOCUMENT';
export const CLOSE_DOCUMENT = 'CLOSE_DOCUMENT';
export const DOCUMENT_DATA = 'DOCUMENT_DATA';
export const OPEN_IP_POPUP = 'OPEN_IP_POPUP';
export const CLOSE_IP_POPUP = 'CLOSE_IP_POPUP';
export const IS_IP_CONFIGURED = 'IS_IP_CONFIGURED';
export const IP_CONFIGURED = 'IP_CONFIGURED';
export const ERROR_POPUP = 'ERROR_POPUP';
export const OPEN_CONFIGURATION_MODAL = ' OPEN_CONFIGURATION_MODAL';
export const CLOSE_CONFIGURATION_MODAL = ' CLOSE_CONFIGURATION_MODAL';
export const SET_CONFIGURATION_DATA = 'SET_CONFIGURATION_DATA';
export const OFFLINE_ONLINE_MODE = 'OFFLINE_ONLINE_MODE';
export const OFFLINE_USER_DATA = 'OFFLINE_USER_DATA';
export const GET_ALL_ASSET_LIVE_DATA = 'GET_ALL_ASSET_LIVE_DATA';
export const GET_ALL_USERS_LIST = 'GET_ALL_USER_LIST';
export const SET_NOTIFICATION_DATA = 'SET_NOTIFICATION_DATA';
export const SET_SHARED_ASSET_DATA = 'SET_SHARED_ASSET_DATA';
export const MARK_AS_READ_ID = 'MARK_AS_READ_ID';
export const SET_SELECTED_SHARED_ASSET = 'SET_SELECTED_SHARED_ASSET';

export const All_UNITS = 'ALL_UNITS';
export const All_SECTION_IN_UNIT = 'All_SECTION_IN_UNIT';
export const ALL_ASSET_IN_SECTION = 'ALL_ASSET_IN_SECTION';

export const CUSTOM_SEARCH_FOR_ASSET = 'CUSTOM_SEARCH_FOR_ASSET';


export const SEARCHING_FOR_ASSET = 'SEARCHING_FOR_ASSET';
export const NOT_SEARCHING_FOR_ASSET = 'NOT_SEARCHING_FOR_ASSET';


export const SELECTED_UNIT_VALUE = 'SELECTED_UNIT_VALUE';
export const SELECTED_SECTION_VALUE = 'SELECTED_SECTION_VALUE';


export const ALARM_PAGE_FIRST_TIME_LOADING = 'ALARM_PAGE_FIRST_TIME_LOADING';

export const SELECTED_KKS_TAG_FROM_NOTIFICATION = 'SELECTED_KKS_TAG_FROM_NOTIFICATION';


//Actions for AR DIGI

export const TAGS_BY_DEFAULT_SELECTED = 'TAGS_BY_DEFAULT_SELECTED';
export const TAGS_TRENDS_DATA = 'TAGS_TRENDS_DATA';
export const SET_ASSET_ID = 'SET_ASSET_ID';
export const SHOW_TREND_POPUP = 'SHOW_TREND_POPUP';
export const SET_USER_NAME = 'SET_USER_NAME';
export const CHANGE_PHONE_ORIENTATION = 'CHANGE_PHONE_ORIENTATION';
export const TOGGLE_BETWEEN_GROUP_AND_TAG_VIEW = 'TOGGLE_BETWEEN_GROUP_AND_TAG_VIEW';
export const GRAPH_GROUP_DATA = 'GRAPH_GROUP_DATA';
export const MENU_HEADER_NAME = "MENU_HEADER_NAME";
export const SET_KKS_TAG = 'SET_KKS_TAG'
export const SELECTED_GROUP_TO_SHOW_ON_VIEW = "SELECTED_GROUP_TO_SHOW_ON_VIEW";

export const TOGGLE_HISTORICAL_TOP_BAR = 'TOGGLE_HISTORICAL_TOP_BAR';
export const TOGGLE_BETWEEN_TAGS_AND_GROUP_IN_HISTORICAL = 'TOGGLE_BETWEEN_TAGS_AND_GROUP_IN_HISTORICAL';

export const ALREADY_SELECTED_UNIT_ID_IN_HISTORICAL = 'ALREADY_SELECTED_UNIT_ID_IN_HISTORICAL';
export const ALREADY_SELECTED_HEADER_ID_IN_HISTORICAL = 'ALREADY_SELECTED_HEADER_ID_IN_HISTORICAL';
export const ALREADY_SELECTED_SUBHEADER_ID_IN_HISTORICAL = 'ALREADY_SELECTED_SUBHEADER_ID_IN_HISTORICAL';
export const ALREADY_SELECTED_ASSET_ID_IN_HISTORICAL = 'ALREADY_SELECTED_ASSET_ID_IN_HISTORICAL';
export const ALREADY_SELECTED_ASSET_LIST = 'ALREADY_SELECTED_ASSET_LIST';
export const SELECT_ASSET_EDIT_TO_VIEW = "SELECT_ASSET_EDIT_TO_VIEW";
export const HIS_START_DATE = 'HIS_START_DATE';
export const HIS_END_DATE = 'HIS_END_DATE';
export const CREATED_ASSIGNED_TASKID = "CREATED_ASSIGNED_TASKID";
export const ALREADY_HAVE_CONSENT = 'ALREADY_HAVE_CONSENT';
export const STATUS_COMPLETION_FOR_TASK = 'STATUS_COMPLETION_FOR_TASK';
export const ASSET_ID_SET = 'ASSET_ID_SET';
export const SET_TASK_ID = 'SET_TASK_ID';
export const SET_TRUE_IS_ASSET_SELECTED_TO_VIEW = 'SET_TRUE_IS_ASSET_SELECTED_TO_VIEW';
export const SET_FALSE_IS_ASSET_SELECTED_TO_VIEW = 'SET_FALSE_IS_ASSET_SELECTED_TO_VIEW';
export const CLOSE_HISTORICAL_TOP_BAR='CLOSE_HISTORICAL_TOP_BAR';
export const SET_TENANT_ID = 'SET_TENANT_ID';
export const SAVE_DEVICE_TOKEN = "SAVE_DEVICE_TOKEN";
//Video Call Required Types:
export const SHOW_RESUME_CALL_TOAST = "SHOW_RESUME_CALL_TOAST";
export const SHOW_VIDEO_CALL_NOTIFICATION = 'SHOW_VIDEO_CALL_NOTIFICATION';
export const SHOW_CONTACTS_OF_VIDEO_CALL = 'SHOW_CONTACTS_OF_VIDEO_CALL';
export const SHOW_MEETING_ROOM = 'SHOW_MEETING_ROOM';
export const SHOW_ROOM_NAME = 'SHOW_ROOM_NAME';
export const DO_NOT_SHOW_VIDEO_CALL_NOTIFICATION_AGAIN = 'DO_NOT_SHOW_VIDEO_CALL_NOTIFICATION_AGAIN';


